-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.animal_id_seq;

CREATE SEQUENCE public.animal_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.animal_image_id_seq;

CREATE SEQUENCE public.animal_image_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.breed_id_seq;

CREATE SEQUENCE public.breed_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.color_id_seq;

CREATE SEQUENCE public.color_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.newsletter_id_seq;

CREATE SEQUENCE public.newsletter_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.species_id_seq;

CREATE SEQUENCE public.species_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.color definition

-- Drop table

-- DROP TABLE public.color;

CREATE TABLE public.color (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	color varchar(255) NULL,
	created_on date NULL,
	CONSTRAINT color_pkey PRIMARY KEY (id)
);


-- public.newsletter definition

-- Drop table

-- DROP TABLE public.newsletter;

CREATE TABLE public.newsletter (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NULL,
	created_on timestamp(6) NULL,
	description varchar(255) NULL,
	image bytea NULL,
	title varchar(255) NULL,
	CONSTRAINT newsletter_pkey PRIMARY KEY (id)
);


-- public.species definition

-- Drop table

-- DROP TABLE public.species;

CREATE TABLE public.species (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NULL,
	"name" varchar(255) NULL,
	CONSTRAINT species_pkey PRIMARY KEY (id)
);


-- public.breed definition

-- Drop table

-- DROP TABLE public.breed;

CREATE TABLE public.breed (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NULL,
	created_on date NULL,
	"type" varchar(255) NULL,
	species_id int4 NOT NULL,
	CONSTRAINT breed_pkey PRIMARY KEY (id),
	CONSTRAINT fk562cbno8t7070q0m0po1fki2n FOREIGN KEY (species_id) REFERENCES public.species(id)
);


-- public.animal definition

-- Drop table

-- DROP TABLE public.animal;

CREATE TABLE public.animal (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	background varchar(255) NULL,
	created_on timestamp(6) NULL,
	description varchar(255) NULL,
	birth_date date NULL,
	disabilities bool NULL,
	"name" varchar(255) NULL,
	sex varchar(255) NULL,
	breed_id int4 NOT NULL,
	color_id int4 NULL,
	CONSTRAINT animal_pkey PRIMARY KEY (id),
	CONSTRAINT fk5vuppijm6mptl6xm5g9jhegwh FOREIGN KEY (breed_id) REFERENCES public.breed(id),
	CONSTRAINT fkjm2ql45rhbpyhwsueioa6d5ys FOREIGN KEY (color_id) REFERENCES public.color(id)
);


-- public.animal_image definition

-- Drop table

-- DROP TABLE public.animal_image;

CREATE TABLE public.animal_image (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	image bytea NULL,
	"name" varchar(255) NULL,
	animal_id int4 NOT NULL,
	CONSTRAINT animal_image_pkey PRIMARY KEY (id),
	CONSTRAINT fke1ssstcnvyc678x6acwr2to1a FOREIGN KEY (animal_id) REFERENCES public.animal(id)
);