CREATE TABLE "animal" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar,
  "DoB" date NOT NULL,
  "species" varchar NOT NULL,
  "sex" varchar NOT NULL,
  "breed" varchar,
  "background" varchar,
  "description" varchar NOT NULL,
  "color" varchar,
  "disabilities" boolean
);

CREATE TABLE "animal_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "animal_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "image" bytea NOT NULL
);

ALTER TABLE "animal_image" ADD FOREIGN KEY ("animal_id") REFERENCES "animal" ("id");